#!/usr/bin/python3
import subprocess

result = subprocess.run('git rev-parse --abbrev-ref HEAD', shell=True, capture_output=True, text=True)

branch = result.stdout

if branch == 'main\n':
  prefix = 'fatal: '
  print(prefix + 'Please do not commit to the main branch.')
  exit(1)
