#!/usr/bin/python3
import subprocess

def verify_commit_branch() -> void:
  result = subprocess.run('git rev-parse --abbrev-ref HEAD', shell=True, capture_output=True, text=True)

  branch = result.stdout

  if branch == 'main\n':
    prefix = 'fatal: '
    print(prefix + 'Please do not commit to the main branch.')
    exit(1)


def verify_linter() -> void:
  subprocess.run('echo hoge')
  subprocess.run('echo fuga')


verify_commit_branch()
verify_linter()