#!/usr/bin/python3
import sys
import re
import codecs

print(sys.argv)

path = sys.argv[1]

with codecs.open(path, mode='r', encoding='utf-8') as f:
  commit_message = f.read()
  
  if re.match(r'/#[0-9]+:/', commit_message) == None:
    print('fatal: No issue number at the beginning of the commit message.')
    print('       The accepted format is as follows:')
    print('              #[0-9]+:')
    print()
    print('       The valid example: git commit -m \'#10:Update README.md\'')
    exit(1)